# Generated by Django 3.1.5 on 2021-01-09 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('function_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='price',
            field=models.FloatField(),
        ),
    ]
